### ISSUE TITLE
2023 GOA Shapefiles (October 2022)

### ISSUE THREAD

**Issue by zoyafuso-NOAA** [afsc-gap-products/StationAllocationAIGOA#17]
Can you look at these shapefiles located [here](https://github.com/afsc-gap-products/StationAllocationAIGOA/tree/master/data/GOA/processed_shapefiles):

1) station polygon: [goa_stations_2023.shp](https://github.com/afsc-gap-products/StationAllocationAIGOA/blob/master/data/GOA/processed_shapefiles/goa_stations_2023.shp)
2) strata polygons: [goa_strata_2023.shp](https://github.com/afsc-gap-products/StationAllocationAIGOA/blob/master/data/GOA/processed_shapefiles/goa_strata_2023.shp)
3) Untrawlable areas: [GOA_untrawl_2021.shp](https://github.com/afsc-gap-products/StationAllocationAIGOA/blob/master/data/GOA/processed_shapefiles/GOA_untrawl_2021.shp)

[updated_strata.pdf](https://github.com/afsc-gap-products/StationAllocationAIGOA/blob/master/data/GOA/processed_shapefiles/updated_strata.pdf) is an image of these combined. 

[UT_areas_2021.pdf](https://github.com/afsc-gap-products/StationAllocationAIGOA/blob/master/data/GOA/processed_shapefiles/UT_areas_2021.pdf) shows the 2021 updates to the untrawlable areas. I didn't see any stations that were changed from untrawlable in 2019 to trawlable in 2021. 

I think you have to download files individually if you're accessing them from GitHub.com. I don't know how one would download multiple files unless they cloned the repo.

I am on flex 10/21 so I will get back to you next week

**Comment by MargaretSiple-NOAA** [comment]
Thanks for putting this all together Zack! I am technically also doing a flex day 10/21 but will get to them first thing on Monday.

**Comment by Ned-Laman-NOAA** [comment]
Hey, we're all on flex day Friday! No working allowed-go have fun instead. See you Monday.
